### ISSUE TITLE
support Uint8List in uploadBinary

### ISSUE THREAD

**Issue by bernaferrari** [supabase/storage-dart#10]
I have the following code:

```dart
FilePickerResult? result = await FilePicker.platform.pickFiles();
if (result != null) {
    Uint8List? fileBytes = result.files.first.bytes;
}
```
In Firebase, I could call `FirebaseStorage.instance.ref('uploads/$fileName').putData(fileBytes);`
In Supabase...?
There is `uploadBinary` which receives a BinaryFile(!?) with the mime and the bytes. Should I call result.toInt()? Isn't that just boilerplate? Or is there a better way?

**Comment by phamhieu** [comment]
Good suggestion @bernaferrari, I refactored upload/update binary methods. Can you check out the latest version.

```dart
final uploadBinaryResponse = await client.from('public').uploadBinary(
   'binaryExample.txt',
   fileData,
);
```

**Comment by bernaferrari** [comment]
That seems way nicer, thanks! Now I only need to discover how to get storage working 😭 it is so hard.

**Comment by phamhieu** [comment]
@bernaferrari what issue you are facing? I can also add you to Supabase Slack group if you are interested.

**Comment by bernaferrari** [comment]
I sent an email to the beta email hoping someone would answer. Maybe it is a bug in supabase? Who knows?

This `await client.storage.from('images').list()` returns [].
`await client.storage.from('images').list()`

Ideally something like this would work: `await client.storage.from('images').upload('${item.id}', file)` but I get errors like `new row violates row-level security policy`.

![image](https://user-images.githubusercontent.com/351125/126250279-02c0eb64-5945-4ae0-96b2-0b6db6f2dedc.png)

**Comment by phamhieu** [comment]
@bernaferrari can you send me your slack account? I can invite you to Supabase slack channel. You can get answer faster than email support.

**Comment by bernaferrari** [comment]
bernaferrari2@gmail.com

**Comment by phamhieu** [comment]
for the error above, you need to add Insert policy to your bucket.

**Comment by bernaferrari** [comment]
Thanks. Just fixed here. For some reason I thought public would make them.. public 😅 thanks!

**Comment by phamhieu** [comment]
public buckets means only accessing is public. You will need policy for insert/update/delete

**Comment by bernaferrari** [comment]
My issue, it seems, was that storage.objects has a 'allow all' template, while specific buckets do not :(
