### ISSUE TITLE
App not compiling for the Flutter Web

### ISSUE THREAD

**Issue by ibhavikmakwana** [supabase/storage-dart#11]
I am building a Flutter app using a Supbase, I am getting an issue while building app for the Web.

## Below error what I got

```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
lib/screen/dashboard/profile/store/profile_screen_store.dart:166:43: Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'dart:io'.
 - 'File/*2*/' is from 'package:universal_io/src/io/file.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/universal_io-2.0.4/lib/src/io/file.dart').
            .update('$fileName$imageExt', file);
                                          ^
lib/screen/dashboard/profile/store/profile_screen_store.dart:170:43: Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'dart:io'.
 - 'File/*2*/' is from 'package:universal_io/src/io/file.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/universal_io-2.0.4/lib/src/io/file.dart').
            .upload('$fileName$imageExt', file);
                                          ^
Failed to compile application.

```

## Link to Source code
[profile_screen_store](https://github.com/ibhavikmakwana/supabase_playground/blob/master/lib/screen/dashboard/profile/store/profile_screen_store.dart)

**Comment by MisterJimson** [comment]
You need to use the `universal_io` package, as dart:io doesn't work on web.

**Comment by ibhavikmakwana** [comment]
My bad, Thanks. Closing this.

**Comment by phamhieu** [comment]
@ibhavikmakwana, just a note that on the web you need to use [uploadBinary](https://github.com/supabase/storage-dart/blob/07db261efea765a341af13ca8258cb5e3922eda3/lib/src/storage_file_api.dart#L62). 

Check out the example [here](https://github.com/supabase/supabase/blob/1b094396f9e6d3862016f6ecd7576ba44130f814/examples/flutter-user-management/lib/screens/profile_screen.dart#L106)

**Comment by ibhavikmakwana** [comment]
Sure, Thanks you :)
