### ISSUE TITLE
Support upload with upsert

### ISSUE THREAD

**Issue by Vinzent03** [supabase/storage-dart#7]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to upload/update profile images. They are named by the user id. If the file already exists, an upload fails, so an update is necessary. But an update fails if the file doesn't exist yet. As stated in the [docs](https://supabase.io/docs/reference/javascript/storage-from-upload#upload-file) there is an option to enable upsert for an upload.

## Describe the solution you'd like

Add `upsert` option to `FileOptions`

## Additional context

When using `upload` when the file already exists, the following error is thrown: 
`duplicate key value violates unique constraint "bucketid_objname"`

**Comment by dshukertjr** [comment]
Thank you so much @Vinzent03 for opening this issue! I have added this feature and submitted a PR!
